### PR TITLE
Fix lexical error with `fotmob_get_season_stats()`

### LINKED ISSUE #201: Issue with `fotmob_get_season_stats( )`
I received the following error to call the season stats by using `fotmob_get_season_stats( )`. How can I solve this? 

```
> epl_team_xg_2021 <- fotmob_get_season_stats(
+   country = "ENG",
+   league_name = "Premier League",
+   season_name = "2020/2021",
+   stat_name = "Expected goals",
+   team_or_player = "team"
+ )

Error: lexical error: invalid char in json text.
                                       NA
                     (right here) ------^
```

### PR DESCRIPTION
**Pull request by tonyelhabr**
It seems that the custom `.fromJSON()` function fails but `jsonlite::fromJSON()` succeeds the stats page for some reason. I've created the function `safely_from_json()` that tries `.fromJSON()` first and then `jsonlite::fromJSON()` if the former fails.

Additionally, I made some updates to accommodate changes with the JSON returned for league stats. (In particular, the API used to return one list element per season for a given league, but this is no longer the case.)

Fixes #201

### CODE REVIEW

File: R/fotmob_helpers.R [hunk 1]
```diff
@@ -8,14 +8,14 @@
...
 }
 
 #' @importFrom stringr str_extract
 .fotmob_get_build_id <- function() {
   meta <- .fotmob_extract_meta()
   meta %>%
     stringr::str_extract('(?<=\\"buildId\\"[:]).*(?=\\,\\"isFallback\\")') %>%
-    .fromJSON()
-
+    safely_from_json() %>%
```
Comment (tonyelhabr) [inline R/fotmob_helpers.R:19]: using `safely_from_json()` here even though `.fromJSON()` was working fine here... seems like a good idea to use `safely_from_json()` in case `.fromJSON()` breaks but `jsonlite::fromJSON()` works

**Comment by tonyelhabr** [comment]
> It seems that the custom `.fromJSON()` function fails but `jsonlite::fromJSON()` succeeds the stats page for some reason. I've created the function `safely_from_json()` that tries `.fromJSON()` first and then `jsonlite::fromJSON()` if the former fails.
> 
> Additionally, I made some updates to accommodate changes with the JSON returned for league stats. (In particular, the API used to return one list element per season for a given league, but this is no longer the case.)

FWIW i think the reason `.fromJSON()` and `jsonlite::fromJSON()` behave differently in some cases may be due to the parsing of long strings. The two use different approaches (written in C).

File: R/fotmob_leagues.R [hunk 2]
```diff
@@ -241,21 +239,18 @@ fotmob_get_league_matches <- function(country, league_name, league_id, cached =
   )
 }
 
-.fotmob_extract_data_from_page_props <- function(resp) {
```
Comment (tonyelhabr) [inline R/fotmob_leagues.R:244]: it seems that this no longer works... it's ok tho, since i only ever used this as a "backup" for extracting data

File: R/fotmob_stats.R [hunk 3]
```diff
@@ -153,39 +150,60 @@
...
-      purrr::keep(isTRUE) %>%
       names()
 
     extract_options <- function(season) {
-      all_stats_df <- stats[[season]][[sprintf("%ss", team_or_player)]] %>%
-        dplyr::distinct(.data[["header"]], .data[["name"]], .data[["fetchAllUrl"]])
-      season_id <- all_stats_df$fetchAllUrl %>% dirname() %>% basename() %>% unique()
-      stats_df <- all_stats_df %>% dplyr::distinct(.data[["header"]], .data[["name"]])
+
+      link <- stats$seasonStatLinks |>
```
Comment (tonyelhabr) [inline R/fotmob_stats.R:165]: this needed major re-factoring due to changes made by fotmob

**Comment by tonyelhabr** [comment]
looks like the test failures are for transfermarket functions

**Comment by JaseZiv** [comment]
> > It seems that the custom `.fromJSON()` function fails but `jsonlite::fromJSON()` succeeds the stats page for some reason. I've created the function `safely_from_json()` that tries `.fromJSON()` first and then `jsonlite::fromJSON()` if the former fails.
> > Additionally, I made some updates to accommodate changes with the JSON returned for league stats. (In particular, the API used to return one list element per season for a given league, but this is no longer the case.)
> 
> FWIW i think the reason `.fromJSON()` and `jsonlite::fromJSON()` behave differently in some cases may be due to the parsing of long strings. The two use different approaches (written in C).

Really neat pickup!

**Comment by JaseZiv** [comment]
> looks like the test failures are for transfermarket functions

I'll sort these in a new PR over the next few days

**Review by JaseZiv — APPROVED** [review]

**Review by JaseZiv — CHANGES_REQUESTED** [review]
Actually, noticed some of the fotmob load functions were also throwing errors:

```
── Failure ('test-load.R:82'): load_fotmob_matches_by_date() works ─────────────
Error: Error: R CMD check found ERRORs
ncol(epl_matches) not equal to `n_cols_match_details`.
Execution halted
1/1 mismatches
[1] 39 - 41 == -2
── Failure ('test-load.R:86'): load_fotmob_matches_by_date() works ─────────────
ncol(epl_matches) not equal to `n_cols_match_details`.
1/1 mismatches
[1] 39 - 41 == -2
```

**Comment by tonyelhabr** [comment]
> Actually, noticed some of the fotmob load functions were also throwing errors:
> 
> ```
> ── Failure ('test-load.R:82'): load_fotmob_matches_by_date() works ─────────────
> Error: Error: R CMD check found ERRORs
> ncol(epl_matches) not equal to `n_cols_match_details`.
> Execution halted
> 1/1 mismatches
> [1] 39 - 41 == -2
> ── Failure ('test-load.R:86'): load_fotmob_matches_by_date() works ─────────────
> ncol(epl_matches) not equal to `n_cols_match_details`.
> 1/1 mismatches
> [1] 39 - 41 == -2
> ```

Ah, I missed those. Just made a fix and looks like they're passing now!

**Comment by JaseZiv** [comment]
> > Actually, noticed some of the fotmob load functions were also throwing errors:
> > ```
> > ── Failure ('test-load.R:82'): load_fotmob_matches_by_date() works ─────────────
> > Error: Error: R CMD check found ERRORs
> > ncol(epl_matches) not equal to `n_cols_match_details`.
> > Execution halted
> > 1/1 mismatches
> > [1] 39 - 41 == -2
> > ── Failure ('test-load.R:86'): load_fotmob_matches_by_date() works ─────────────
> > ncol(epl_matches) not equal to `n_cols_match_details`.
> > 1/1 mismatches
> > [1] 39 - 41 == -2
> > ```
> 
> Ah, I missed those. Just made a fix and looks like they're passing now!

Awesome stuff! Thanks heaps

**Review by JaseZiv — APPROVED** [review]

File: R/fotmob_stats.R (hunk 3 above)
Comment (tonyelhabr) [reply R/fotmob_stats.R:165]: ah, just realized i used the base pipe here! i can fix this next time i make a PR
