### PR TITLE
Bug fixes for `fotmob_get_match_players()`

### LINKED ISSUE #298: fotmob_get_match_players
Hi!

It seems like Fotmob have changed things around as scraping player stats now looks like this: 

Skjermbilde 2023-07-03 kl  19 14 17

Wondering if this is fixable?

---
```r
library(worldfootballR)
packageVersion("worldfootballR")
[1] ‘0.6.3.7’

fotmob_matches <- c(3609994, 3610132)
players <- fotmob_get_match_players(fotmob_matches)
```

### PR DESCRIPTION
**Pull request by tonyelhabr**
Bug fixes for `fotmob_get_match_players()`

1. Remove hard-coded by-row assignment in `fotmob_get_match_players()` (fixes #298)
2. Fix failure in cases where players do not have stats (observed in [recent R CMD check](https://github.com/JaseZiv/worldfootballR/actions/runs/5570217380/job/15082665666))

### CODE REVIEW

File: R/fotmob_players.R [hunk 1]
```diff
@@ -114,9 +115,13 @@
     "away_team_color" = .ppc(p, "teamData", "away", "color", n = n)
   )
 
-  rows$stats <- vector(mode = "list", length = nrow(stats))
-  for (i in 1:nrow(rows)) {
-    rows[i, ]$stats <- list(stats[1, ])
```
Comment (tonyelhabr) [inline R/fotmob_players.R:119]: i had accidentally left this hard-coded as `stats[1, ]` when it should be `stats[i, ]`. this resolves the issue noted [here](https://github.com/JaseZiv/worldfootballR/issues/298#issuecomment-1644913918)

File: R/fotmob_players.R [hunk 2]
```diff
@@ -114,9 +115,13 @@
...
+  if (does_not_have_stats) {
+    rows$stats <- list(NULL)
```
Comment (tonyelhabr) [inline R/fotmob_players.R:119]: this resolves the failed test [here](https://github.com/JaseZiv/worldfootballR/blob/e8daa4bbffae616ed28ecfba5961f544d3cdb81f/tests/testthat/test-fotmob.R#L482-L483)

File: R/fotmob_players.R [hunk 3]
```diff
@@ -114,9 +115,13 @@
     "away_team_color" = .ppc(p, "teamData", "away", "color", n = n)
   )
 
-  rows$stats <- vector(mode = "list", length = nrow(stats))
-  for (i in 1:nrow(rows)) {
-    rows[i, ]$stats <- list(stats[1, ])
+  if (does_not_have_stats) {
+    rows$stats <- list(stats)
```
Comment (tonyelhabr) [inline R/fotmob_players.R:119]: this resolves the failing test [here](https://github.com/JaseZiv/worldfootballR/blob/e8daa4bbffae616ed28ecfba5961f544d3cdb81f/tests/testthat/test-fotmob.R#L482-L483)

**Review by JaseZiv — APPROVED** [review]
lgtm
