### PR TITLE
Fix `tm_player_transfer_history`

### LINKED ISSUE #342: `tm_player_transfer_history()` failing due to not being available in the HTML of transfermarkt
Without using some form of browser automation, player transfer histories are no longer able to be scraped by `tm_player_transfer_history()` in its current form.

Will open this issue and try to incorporate the work @tonyelhabr did using chromote to obtain certain FBREF data points.

### PR DESCRIPTION
**Pull request by tonyelhabr**
The "base" fields that used to be returned by `tm_player_transfer_history()` are no longer provided via server-side rendered HTML. Instead, the data is loaded client-side after an API call. This PR refactors the logic to replicate the API call that a browser would make to retrieve the "base" fields like `team_from`, `market_value`, etc.

The logic for the "extra" columns like `country_from`, `contract_expiry` remains the same, although I've refactored it to be a little more elegant (using `purrr::map()`).

Fixes #342.

### CODE REVIEW

File: tests/testthat/test-transfermarkt.R [hunk 1]
```diff
@@ -11,24 +11,58 @@ test_that("tm_player_market_values() works", {
 
 })
 
+test_that("tm_player_transfer_history() works", {
+  testthat::skip_if_offline()
+  testthat::skip_on_cran()
+
+  ## multiple URLs
+  transfer_data <- tm_player_transfer_history(
```
Comment (tonyelhabr) [inline tests/testthat/test-transfermarkt.R:19]: augmented the test a bit while i was at it.

- explicit testing for multiple URLs
- explicit testing of `get_extra_info`
- checks for exact column names (this should be less frail than what we used to do for fotmob since we explicitly define the column names in the function code)

File: R/player_transfer_history.R [hunk 2]
```diff
@@ -9,155 +21,183 @@
...
+          .x[["country_from"]] <- country_from
+          .x[["country_to"]] <- country_to
+          .x
         }
-
-      }
-
-      each_player_df <- rbind(each_player_df, each_row_df)
+      ) %>%
+        ## for backwards compatability
```
Comment (tonyelhabr) [inline R/player_transfer_history.R:162]: i.e. return the columns in the same order that they used to be returned

File: R/player_transfer_history.R [hunk 3]
```diff
@@ -9,155 +21,183 @@
...
+          "team_to" = .x[["to"]][["clubName"]],
+          "market_value" = .convert_value_to_numeric(.x[["marketValue"]]),
+          "transfer_value" = .convert_value_to_numeric(.x[["fee"]]),
+          "transfer_type" = .standardize_fee(.x[["fee"]])
+        )
+      }
+    )
+
+    # Executed if the user wants to get more info. Contains: Contract Expiring date + Days remaining. From which countries was the transfer.
+    res <- if (isTRUE(get_extra_info)) {
```
Comment (tonyelhabr) [inline R/player_transfer_history.R:76]: no actual logic changes for `get_extra_info` retrieval. just better spacing, etc.

**Review by JaseZiv — APPROVED** [review]
This is awesome! Thanks heaps for addressing @tonyelhabr
