### PR TITLE
Fix fotmob team color in `fotmob_get_match_details()`

### LINKED ISSUE #271: Error in fotmob_get_match_details()
Trying to get match shooting-locations from fotmob using fotmob_get_match_details()
using this code:

match_details <- fotmob_get_match_details(4077010)
match_details

getting this error:

> match_details <- fotmob_get_match_details(4077010) 
Error: arguments imply differing number of rows: 1, 0 > match_details 
A tibble: 0 x 1 # ... with 1 variable: match_id <int> 
i Use `colnames()` to see all variable names

### PR DESCRIPTION
**Pull request by tonyelhabr**
Fotmob slightly changed the format of the JSON for match details. Specifically, they provide 4 colors per team now. I'm just plucking out the first `color`.

image

Fixes #271.

### CODE REVIEW

File: tests/testthat/test-fotmob.R [hunk 1]
```diff
@@ -409,12 +409,12 @@ test_that("fotmob_get_match_team_stats() works", {
   match_team_stats <- fotmob_get_match_team_stats(c(3609987, 3609979))
 
   expect_gt(nrow(match_team_stats), 0)
-  expect_setequal(colnames(match_team_stats), expected_match_team_stats_cols)
+  expect_true(all(expected_match_team_stats_cols %in% colnames(match_team_stats)))
```
Comment (tonyelhabr) [inline tests/testthat/test-fotmob.R:412]: drive by test fixes... the strict equality check was failing for some `stat_*` columns, which Fotmob occasionally renames or removes.

**Review by JaseZiv — APPROVED** [review]
lgtm
