### PR TITLE
Fix team ids in `fotmob_get_match_players`

### LINKED ISSUE #93: home_team_id and away_team_id identical using `fotmob_get_match_players()`
When running the below code, the resulting data frame is returning identical team IDs for both `home_team_id` and `away_team_id`

```
worldfootballR::fotmob_get_match_players(3609987)
```

image

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] here_1.0.1                 forcats_0.5.1             
 [3] stringr_1.4.0              dplyr_1.0.7               
 [5] purrr_0.3.4                readr_2.0.0               
 [7] tidyr_1.2.0                tibble_3.1.6              
 [9] ggplot2_3.3.5              tidyverse_1.3.1           
[11] worldfootballR_0.4.10.2000

loaded via a namespace (and not attached):
 [1] progress_1.2.2    tinytex_0.33      tidyselect_1.1.1 
 [4] xfun_0.29         janitor_2.1.0     haven_2.4.3      
 [7] snakecase_0.11.0  colorspace_2.0-2  vctrs_0.3.8      
[10] generics_0.1.0    utf8_1.2.2        rlang_0.4.11     
[13] pillar_1.6.2      glue_1.4.2        withr_2.4.2      
[16] DBI_1.1.1         selectr_0.4-2     dbplyr_2.1.1     
[19] modelr_0.1.8      readxl_1.3.1      lifecycle_1.0.0  
[22] munsell_0.5.0     gtable_0.3.0      cellranger_1.1.0 
[25] rvest_1.0.1       tzdb_0.1.2        curl_4.3.2       
[28] fansi_0.5.0       broom_0.7.9       Rcpp_1.0.7       
[31] backports_1.2.1   scales_1.1.1      jsonlite_1.7.2   
[34] fs_1.5.0          hms_1.1.0         stringi_1.7.3    
[37] grid_4.1.0        rprojroot_2.0.2   cli_3.0.1        
[40] tools_4.1.0       magrittr_2.0.1    crayon_1.4.1     
[43] pkgconfig_2.0.3   ellipsis_0.3.2    prettyunits_1.1.1
[46] xml2_1.3.2        reprex_2.0.1      lubridate_1.7.10 
[49] assertthat_0.2.1  httr_1.4.2        rstudioapi_0.13  
[52] R6_2.5.0          compiler_4.1.0  
```

@tonyelhabr

### PR DESCRIPTION
**Pull request by tonyelhabr**
Fixes #93

### CODE REVIEW

File: R/fotmob_players.R [hunk 1]
```diff
@@ -167,8 +168,12 @@ fotmob_get_match_players <- function(match_ids) {
...
       tibble::as_tibble()
+    ## Overwrite the existing variables since the away team value is "bad". See https://github.com/JaseZiv/worldfootballR/issues/93
+    res$home_team_id <- table$teams[1]
+    res$away_team_id <- table$teams[2]
+    res
   }
 
   fp <- purrr::possibly(f, otherwise = tibble::tibble())
-  f(url)
+  fp(url)
```
Comment (tonyelhabr) [inline R/fotmob_players.R:178]: whoops! should have been using the possibly wrapped version before

File: R/fotmob_players.R [hunk 2]
```diff
@@ -61,10 +62,10 @@ fotmob_get_match_players <- function(match_ids) {
           xt2 <- matrix(
             as.numeric(gsub("%", "", xt)),
             ncol = ncol(xt)
-          )
+          ) %>%
+            tibble::as_tibble()
```
Comment (tonyelhabr) [inline R/fotmob_players.R:66]: moved this to avoid the warning that tibble prints out about `as_tibble.matrix` the first time this is called in a session
