### PR TITLE
Fix duplicate player hrefs in FBref functions

### LINKED ISSUE #327: fb_player_match_logs with duplicate end years
It appears that when getting the match logs from players that have two same years as the season end year (when they transfer between leagues who have different calendars) the function is unable to choose between the seasons

```r

> messi_summary2022 <- fb_player_match_logs("https://fbref.com/en/players/d70ce98e/Lionel-Messi", season_end_year = 2022, stat_type = 'summary')
> messi_summary2023 <- fb_player_match_logs("https://fbref.com/en/players/d70ce98e/Lionel-Messi", season_end_year = 2023, stat_type = 'summary')
Error in httr::handle(url) : length(url) == 1 is not TRUE

> busquets_summary2022 <- fb_player_match_logs("https://fbref.com/en/players/5ab0ea87/Sergio-Busquets", season_end_year = 2022, stat_type = 'summary')
> busquets_summary2023 <- fb_player_match_logs("https://fbref.com/en/players/5ab0ea87/Sergio-Busquets", season_end_year = 2023, stat_type = 'summary')
Error in httr::handle(url) : length(url) == 1 is not TRUE

```

### PR DESCRIPTION
**Pull request by tonyelhabr**
It was possible for FBref functions that returned `Player_Href` (added with #328) to return "bad" links when there are different players with the same exact name. This is fixed by simply joining the hrefs back to the rest of the dataframe rather than doing a lookup by name. The new approach may encounter an error if a player does not have an FBref page for some reason, although I've never actually seen that before.

Fixes #327.

### CODE REVIEW

File: R/fb_league_stats.R [hunk 1]
```diff
@@ -48,7 +48,7 @@
       return(tibble::tibble())
     }
     renamed_table <- .rename_fb_cols(tables[[3]])
-    renamed_table[renamed_table$Rk != "Rk", ]
```
Comment (tonyelhabr) [inline R/fb_league_stats.R:51]: drive by fix 😅

File: R/get_advanced_match_stats.R [hunk 2]
```diff
@@ -3,13 +3,10 @@
...
   player_elements <- xml2::xml_find_all(parent_element, player_xpath)
-  players <- stats::setNames(
-    xml2::xml_attr(player_elements, "href"),
-    xml2::xml_text(player_elements)
-  )
+  player_hrefs <- xml2::xml_attr(player_elements, "href")
   res <- dplyr::mutate(
     df,
-    "Player_Href" = players[df$Player],
+    "Player_Href" = player_hrefs,
```
Comment (tonyelhabr) [inline R/get_advanced_match_stats.R:9]: this assumes the number of player links will be equal to the number of rows in `df`. this is probably a fine assumption

**Review by JaseZiv — APPROVED** [review]
lgtm
